services:
  shard1:
    image: mongo:6.0
    container_name: mongo-shard
    command: >
      mongod --shardsvr
             --replSet %SHARD_NAME%
             --port 27017
             --bind_ip_all
    ports:
      - "27017:27017"
    volumes:
      - shard-data:/data/db

volumes:
  shard-data: